[package]
name = "okari"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
comrak = { version = "0.10", default-features = false }
yaml-rust = "0.4"
walkdir = "2.3.2"
chrono = "0.4.19"
